Repository amritrau/shadow-hunters, pull requests merged in 2020-10, with the labels that each got.

#198 Escape HTML before broadcasting chat messages
  shadow-hunters/app.py
Labels: bug, urgent

#200 Explain reserved names & fix typos
  shadow-hunters/app.py
  shadow-hunters/helpers.py
  shadow-hunters/hermit.py
Labels: back-end, bug

#202 Correct rules page formating and add links to GitHub
  templates/room.html
  templates/rules.html
Labels: front-end

#203 Fix link that doesn't open in new tab
  templates/room.html
Labels: front-end

#219 Attribution update
  README.md
  templates/rules.html
Labels: front-end
